config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'signup', to: 'users#new'
  resources 'users', except: [:new]

  get 'about', to: 'pages#about'
  resources :articles

  # session handling
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # categories
  resources 'categories'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true, length: {minimum: 10}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord 

  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 20}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_secure_password
  before_save {self.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, 
    presence: true, 
    uniqueness: {case_sensitive: false}, 
    length: {minimum: 3, maximum: 25}
  validates :email, 
    presence: true, 
    uniqueness: {case_sensitive: false}, 
    format: {with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    return @current_user
  end

  def logged_in?
    return current_user!= nil
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user_or_admin, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    require_user
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
    def article_params
      return params.require(:article).permit(:title, :description, :category_ids => [])
    end

    def set_article
      @article = Article.find params[:id]
    end

    def require_same_user_or_admin
      if current_user != @article.user && !current_user.admin
        redirect_to articles_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "You have created a new category!"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
      flash[:success] = "You have successfully updated a category!"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  private 
    def category_params
      return params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || !current_user.admin
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to user_path(current_user) if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user_info = params[:sessions]

    puts params[:session]
    puts "hello"
    puts params[:sessions]

    user = User.find_by_email(user_info[:email].downcase)
    if user && user.authenticate(user_info[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back #{user.username}!"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Invalid email or password. Please try again."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out."
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the alpha blog!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      flash[:success] = "You have changed your information!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 9)
  end

  def destroy
    user = @user
    @user.destroy
    flash[:danger] = "#{user.username} and all his/her articles have been deleted"
    @users = User.paginate(page: params[:page], per_page: 9)
    render 'index'
  end

  private
    def user_params
      return params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end
    
    def require_same_user
      if !logged_in?
        redirect_to root_path
      elsif current_user != @user
        redirect_to user_path(current_user)
      end
    end

    def require_admin
      if !logged_in? || !current_user.admin
        redirect_to users_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    img_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    return image_tag(img_src, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class = "row">
  <div class = "col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class = "form-group">
      <div class = "col-sm-2 col-sm-offset-1 control-label">
        <%= f.label :title %>
      </div>
      <div class = "col-sm-6">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true%>
      </div>
    </div>        
    <div class = "form-group">
      <div class = "col-sm-2 col-sm-offset-1 control-label">
        <%= f.label :description %>
      </div>
      <div class = "col-sm-6">
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article"%>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
            <div class="checkbox-inline input_checkbox">
              <%= cb.check_box(class: "checkbox") + cb.text%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit class: "btn btn-primary btn-large" %>
      </div>
    </div>
  <% end %>
  </div>
</div>  


<div class = "col-sm-offset-3 col-sm-6">
  [ <%= link_to  "Cancel request and return to articles listing", articles_path%> ]
</div>

app/views/articles/edit.html.erb
<h3 align="center"> Edit an existing article </h3>
<%= render 'form' %>

app/views/articles/index.html.erb
<h3 align = "center" style="margin-bottom:20px">All Articles</h3>

<div class = "col-xs-8 col-xs-offset-2" align = "right" style = "margin-bottom:20px">
  <%=link_to "New Article", new_article_path, class:'btn btn-md btn-success'%>
</div>

<div align="center">
  <%= will_paginate %>
</div>

<%= render 'shared/articles', articles: @articles%>

<div align="center">
  <%= will_paginate %>
</div>
    

app/views/articles/new.html.erb
<h3 align = "center">Create an article</h3><br/>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class = "well col-xs-8 col-xs-offset-2">
  <div>
    <%= gravatar_for(@article.user, size: 40) if @article.user%>
    <div class = "article-description" style = "margin-top:5px">
      Contributed by: <strong><%= @article.user.username if @article.user %></strong>
    </div>
  </div>
  <div class = "article-title" style = "margin-top:15px">
    <%= @article.title %>
  </div>
  <%= render 'shared/categories', article: @article %>
  <div class = "article-description" style = "margin-top:15px">
    <%= simple_format(@article.description)%></br>
  </div>
  <div class = "article-actions">
    <%= link_to 'Back to articles listing', articles_path, class: "btn btn-sm btn-primary"%>
    <% if current_user && current_user == @article.user %>
      <%= link_to 'Delete this article', 
        article_path(@article), 
        method: :delete, 
        data: {confirm: "Are you sure?"}, 
        class: 'btn btn-sm btn-danger'%>
      <%= link_to 'Edit this article', 
        edit_article_path(@article), 
        class: "btn btn-sm btn-success"%>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<div class = "row">
  <div class = "col-xs-12">
    <%= form_for(@category, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      <div class="form-group">
        <label class="col-sm-2 col-sm-offset-1 control-label">Category Name</label>
        <div class="col-sm-6">
          <%= f.text_field :name, class: 'form-control', placeholder: "Category name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <dig class="col-sm-6 col-sm-offset-3">
          <%= f.submit "Submit Category", class: "btn btn-primary btn-large" %>
        </div>
      </div>
    <% end %>  
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'shared/errors', obj: @category %>
<h3 align="center" style='margin-bottom:30px'>Edit an existing category</h3>

<%= render 'categories/form' %>

app/views/categories/index.html.erb
<h3 align = "center" style="margin-bottom:20px">
  All Categories <%=(link_to "(+)", new_category_path) if (logged_in? && current_user.admin)%>
</h3>

<div class='col-xs-8 col-xs-offset-2'>
  <% i = 0 %>
  <% while i < @categories.size %>
    <div class='row' align='center'>
      <%= render 'shared/category', category: @categories[i] %>
      <% if @categories[i + 1] %>
        <%= render 'shared/category', category: @categories[i + 1] %>
      <% end %>
      <% if @categories[i + 2] %>
        <%= render 'shared/category', category: @categories[i + 2] %>
      <% end %>
      <% i += 3 %>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/errors', obj: @category %>
<h3 align="center" style='margin-bottom:30px'>Create a new category</h3>

<%= render 'categories/form' %>

app/views/categories/show.html.erb
<h3 align='center' style='margin-bottom:15px'>All Articles for Category: <i><%= @category.name %></i></h3>

<%= render 'shared/articles', articles: @articles %>.
<div align="center">
  <%= will_paginate @articles%>
</div<

app/views/layouts/_footer.html.erb
<div class = "container">
  <footer class="footer">
    <small>
      Copyright &copy; alpha-blogs. <br/>
      Created by: Moses Liu
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class = "row">
  <div class = "col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg|%>
      <div class = 'alert alert-<%="#{name}"%> alert-dismissable'>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong><%= name == "success" ? name.capitalize + ": " : ""%></strong><%=msg%>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.erb
<nav class="navbar navbar-default" style="z-index:1">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to  "Alpha Blog", root_path, class: "navbar-brand", id: "logo"%>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %>
        <li><%= link_to "Users", users_path %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% for category in Category.all %>
              <li role="separator" class="divider"></li>
              <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
          </ul>
        </li>
        <% if logged_in?%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %>
              <% if logged_in? && current_user.admin %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "New Category", new_category_path %><li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "(Admin)" if current_user.admin%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Your Profile", user_path(current_user)%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Edit Your Profile", edit_user_path(current_user)%></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path%></li>
          <li><%= link_to "Log In", login_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class = "container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<html>
	<body>
		<div class = "bg"></div>
			<div class = "whiteFilm">
				<div class="titleBlock" style="margin-top:80px">
					About 
					<%= link_to 'Alpha Blog', articles_path%>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>

<html>
	<body>
			<div class = "bg"></div>
				<div class = "whiteFilm">
					<div class="jumbotron titleBlock" style="margin-top:100px">
						<h1>Welcome to Alpha Blog</h1>
						<p>A place to share. A place to grow.</p><br/>
						<%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-default"%>
					</div>
				</div>
			</div>
	</body>
</html>

app/views/shared/_articles.html.erb
<% for article in articles %>
  <div class = "row">
    <div class = "col-xs-8 col-xs-offset-2">
      <div class = "well well-lg">
        <%=link_to "#{article.title}", article_path(article), class: "article-title" %>
        <%= render 'shared/categories', article: article %>
        <div class = "article-description" style= "margin-top:15px">
          <%=simple_format(article.description)%>
          <div class = "article-meta" style = "margin-top:20px">
            <small>
              Created by <strong><%=(link_to article.user.username, user_path(article.user), class: "article-meta") if article.user%></strong>
              <%= time_ago_in_words(article.created_at) %> ago.<br/>
              Last updated <%= time_ago_in_words(article.updated_at) %> ago.<br/>
            </small>
          </div>
        </div>
        <div class = "article-actions" style="margin-top:5px">
          <% if logged_in? && (current_user == article.user || current_user.admin) %>
            <%=link_to "Edit", edit_article_path(article), class:'btn btn-sm btn-warning'%>
            <%=link_to "Delete", article_path(article), 
              method: :delete, 
              data: {confirm: "Are you sure?"}, 
              class: 'btn btn-sm btn-danger'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_categories.html.erb
<% if article.categories.any? %>
  <div class = "category-label">
    Categories: 
    <% for category in article.categories %>
      <%= link_to category.name, category_path(category), class: "category-link" %>
      <span> | </span>
    <% end %>
  </div>
<% end %>

app/views/shared/_category.html.erb
<div class = "well col-xs-4">
  <div align = "center">
     <%= link_to category.name, category_path(category), class: "article-title" %>
  </div>
  <div class="article-description">
    <%= pluralize(category.articles.count, "Articles")%>
  </div>
  <% if logged_in? and current_user.admin? %>
    <div style="margin-top: 15px", align="center">
      <%= link_to "Edit Category Name", edit_category_path(category), class: "btn btn-xs btn-warning" %>
    </div>
    <div style="margin-top: 5px", align="center">
      <%= link_to "Delete Category", 
        category_path(category), 
        method: :delete, 
        data: {confirm: "Are you sure you want to delete this category?"},
        class:"btn btn-xs btn-danger" %>
    </div>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class = "row">
  <div class = "col-xs-8 col-xs-offset-2">
    <div class = "panel panel-danger">
      <div class = "panel-heading">
        <h2 class = "panel-title">
          <%= pluralize(obj.errors.count, "errors")%>
          prohibited this article from being saved
        </h2>
        <div class = "panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_user.html.erb
<div class="col-xs-4 col-md-4">
  <%= link_to user_path(user) do %>
    <div class="thumbnail">
      <div class="user-username" style="padding-bottom:10px">
        <%= user.username %>
      </div>
      <%=gravatar_for(user)%>
      <div class='user-contributions'>
        Contributed <%= pluralize(user.articles.size, "Article")%>
      </div>
      <% if logged_in? && current_user.admin%>
        <div>
          <%= link_to "Delete User", 
            user_path(user), 
            method: :delete,  
            data: {confirm: "Are you sure you want to delete this user and all his/her articles?"},
            class: "btn btn-danger btn-sm"
          %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class = "row">
  <div class = "col-xs-12">
    <%= form_for(@user, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      <div class="form-group">
        <label class="col-sm-2 col-sm-offset-1 control-label">Username</label>
        <div class="col-sm-6">
          <%= f.text_field :username, class: 'form-control', placeholder: "Username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 col-sm-offset-1 control-label">Email</label>
        <div class="col-sm-6">
          <%= f.email_field :email, class: 'form-control', placeholder: "Email"%>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 col-sm-offset-1 control-label">Password</label>
        <div class="col-sm-6">
          <%= f.password_field :password, class: 'form-control', placeholder: "Password"%>
        </div>
      </div>
      <div class="form-group">
        <dig class="col-sm-6 col-sm-offset-3">
          <%= f.submit button_label, class: "btn btn-primary btn-large" %>
        </div>
      </div>
    <% end %>  
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/errors', obj: @user %>
<h3 align='center' style='margin-bottom:30px'> Edit Info</h3>

<%= render 'form', button_label: 'Commit Changes'%>

app/views/users/index.html.erb
<h3 align = "center" style="margin-bottom:25px">Meet the Alpha Bloggers</h3>

<div align = "center">
  <%= will_paginate @users %>
</div>

<div class='col-xs-8 col-xs-offset-2'>
  <% i = 0 %>
  <% while i < @users.size %>
    <div class='row' align='center'>
      <%= render 'shared/user', user: @users[i] %>
      <% if @users[i + 1] %>
        <%= render 'shared/user', user: @users[i + 1] %>
      <% end %>
      <% if @users[i + 2] %>
        <%= render 'shared/user', user: @users[i + 2] %>
      <% end %>
      <% i += 3 %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>
<h3 align='center' style='margin-bottom:30px'> Sign Up</h3>

<%= render 'form', button_label: "Sign up"%>

app/views/users/show.html.erb
<h3 align='center' style='margin-bottom:15px'>
  <% if logged_in? && @user == current_user%>
    Your Articles
  <% else %>
    <%= @user.username %>'s Articles
  <% end %>
</h3>

<div class='row' align='center'>
  <div class = 'col-xs-8 col-xs-offset-2' style='margin-bottom:15px'>
    <%= gravatar_for@user, size: 100%>
  </div>
</div>

<div align="center">
  <%= will_paginate @user_articles %>
</div>

<%= render 'shared/articles', articles: @user_articles %>